name: calculetor
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:


  # auto_size_text: ^3.0.0
  better_player: ^0.0.84
  cached_network_image: ^3.4.1
  camera: ^0.11.0+2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  # path_provider: ^2.1.4
  math_expressions: ^2.6.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  # video_player: ^2.9.1
  # youtube_explode_dart: ^2.2.2
  # flutter_launcher_icons: ^0.13.1
  # flutter_staggered_grid_view: ^0.7.0
  # google_fonts: ^6.2.1
  # http: ^1.2.1
  # image_picker: ^1.1.0
  # path_provider: ^2.1.3
  # permission_handler: ^11.3.1
  # shared_preferences: ^2.2.3
  # video_player: ^2.8.6
  # youtube_explode_dart: ^2.2.0
  # auto_size_text: ^3.0.0
  # cached_network_image: ^3.3.1
  # camera: ^0.10.5+9
  # firebase_core: ^2.31.1
  # firebase_remote_config: ^4.4.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.6
  # flutter_media_downloader: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/calculetor.png"
  min_sdk_android: 21 

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
